name: Manual Job Template

on:
  workflow_call:
    inputs:
      job_name:
        required: true
        type: string

jobs:
  manual-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: echo "Ejecutando Job Manual ${{ inputs.job_name }}"
