name: Test Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  job-a:
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: echo "Ejecutando Job A"

  job-b:
    needs: job-a
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: echo "Ejecutando Job B"

  job-c:
    needs: job-b
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: echo "Ejecutando Job C"

  job-d:
    needs: job-a
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: echo "Ejecutando Job D"

  job-e:
    needs: job-a
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: echo "Ejecutando Job E"

  job-f:
    needs: job-e
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: echo "Ejecutando Job F"

  test-manual:
    uses: ./.github/workflows/run-manual.yml
    if: ${{ github.event_name == 'workflow_dispatch' }}
    with:
      job_name: "Manual desde B"
      dependency: "job-b"
